services:
  backend:
    build: ./backend
    ports:
      - "8005:8005"
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql+psycopg2://sebastian@host.docker.internal:5432/adsolve
